### ISSUE TITLE
-webkit prefixes for transition and transform

### ISSUE THREAD

**Issue by abstracthat** [berzniz/react-overdrive#14]
Thanks for this great lib! Can we add -webkit prefixes for transition and transform to support older safari? Would only be a few extra lines of code. Happy to make a PR for this if you are okay with it.

**Comment by berzniz** [comment]
Sure. Go for it, I'll gladly merge a PR. I'd try to create a naive prefixer function so it will be as DRY as possible

**Comment by berzniz** [comment]
I'm building and releasing the new version soon (0.0.4)

**Comment by berzniz** [comment]
published to npm
