### ISSUE TITLE
Add an option to customise component that is inserted when using Overdrive

### ISSUE THREAD

**Issue by gryzzly** [berzniz/react-overdrive#19]
Similar to `<ReactCSSTransitionGroup>` there could be a `component` prop and `className` prop to customise what will wrap the children provided to Overdrive. Otherwise it is quite easy to break layout with an unexpected `<div>`.

**Comment by berzniz** [comment]
All properties are available on the `<Overdrive/>` component, for example:
```jsx
<Overdrive className="some-class" style={{display: 'inline-block'}}>
  ...
</Overdrive>
```

This should allow customizing the added `<div/>` in any way needed. Does this solution meet the needs you decribed? or choosing the tag important (`span` / `li` / etc... instead of `div`)?
