### ISSUE TITLE
Use refs instead of ids?

### ISSUE THREAD

**Issue by VinSpee** [berzniz/react-overdrive#2]
Hi! Do you think it might be more React™ To use refs instead of ids?

**Comment by berzniz** [comment]
The way it currently works is that two totally different components are "linked" together via the `id` prop. This is a signal to the library that we want to transition from one to the other. Originally I used `key` as the "linking" prop, but decided not to overload the `key`'s purpose.

What did you have in mind with `ref`s?

**Comment by VinSpee** [comment]
Oh I like the idea of key too. Isn't the point of keys to be a unique identifier? Same for ids in the sense of the DOM

**Comment by berzniz** [comment]
I'll do some research on `key` usage and might switch to it and deprecate `id` for backward-compatibility.
