### ISSUE TITLE
AnimationEnd Event

### ISSUE THREAD

**Issue by vasco-santos** [berzniz/react-overdrive#28]
In the context of this module, there are some use cases where it would be important to have an onAnimationEnd prop in the API.

For example, when considering an action on componentDidMound that causes a new render invocation, if the animation provided by **react-overdrive** has not finished yet, it is broken by the new render invocation.

It would be worthwhile to consider adding this prop event to the API provided 😄 .

**Comment by berzniz** [comment]
Before I'm looking into that myself, do you want to try adding it and sending a PR?

**Comment by vasco-santos** [comment]
Sure, I can check it in a few days! 😃
