### ISSUE TITLE
Make unmount requirement optional

### ISSUE THREAD

**Issue by ConneXNL** [berzniz/react-overdrive#31]
Looking at the docs it appears the original component has to be unmounted in order to create a transition.

Would it make sense to add an option that does not require an element to be unmounted and still perform an  "overdrive" transition?

A use case would be a popup / tooltip window that transitions out of the highlighted item but doesn't (always) cover it.

**Comment by berzniz** [comment]
The basic idea of react-overdrive is to transition from one element to another. If you transition the same element, you can use CSS's transitions to achieve that without the need for `react-overdrive`.
