### ISSUE TITLE
Custom ease ?

### ISSUE THREAD

**Issue by muhajirframe** [berzniz/react-overdrive#41]
Is it possible to use custom ease?

**Comment by berzniz** [comment]
It doesn't support it currently, but I'm open to accept a PR for adding it.

A custom `easing` prop can be passed (default can be empty) and then it would need to be applied somewhere here:
```
const transition = {
  transition: `transform ${duration / 1000}s, opacity ${duration / 1000}s`,
  transformOrigin: '0 0 0'
};
```

**Comment by berzniz** [comment]
Thanks @pizza3 - added in version 0.0.10
