### ISSUE TITLE
Library maintence? Point to alternatives?

### ISSUE THREAD

**Issue by madou** [berzniz/react-overdrive#53]
Hi there! Are you still maintaining this project? If not would you point to other libraries who are solving similar problems?

Full disclosure I maintain a library called `yubaba` (https://github.com/madou/yubaba) which has been around for a few years. It solves a similar problem to `react-overdrive` while also providing other animations, a really handy orchestration layer to manage the animations, and a method for consumers to make their own animations.

Cheers

**Comment by berzniz** [comment]
While I don't actively add features or improve it, `react-overdrive` should still work and is a simple solution to the problem.

I just taken a look into `yubaba` and it looks good! I won't be adding links to components I haven't used myself, but people can find this issue and find `yubaba`.
